### ISSUE TITLE
Rename repo to ezsolr-docker

### ISSUE THREAD

**Issue by mauricios** [Aplyca/ezsolr-docker#1]
What this repo really does is to create a Solr Docker image tailored for eZ Publish/Platform from the eZFind distribution we should rename this repo to ezsolr-docker

**Comment by mauricios** [comment]
We should rename the docker image in Docker hub accordingly

**Comment by damaya** [comment]
Hi @mauricios you right, thanks for the feedback, i'll rename this to match solr instead of ezfind.

**Comment by damaya** [comment]
Hi @mauricios closing this issue as solved, the new public image was tested on 2 environments and all is working as expected.

**Comment by damaya** [comment]
The new public image is https://cloud.docker.com/u/aplyca/repository/docker/aplyca/ezsolr, and the source repo is https://github.com/Aplyca/ezsolr-docker
